AWSTemplateFormatVersion: '2010-09-09'
Description: 'NMM Document Processing After Extraction Queue and Lambda Integration'

Parameters:
  LambdaFunctionName:
    Type: String
    Default: nmm_document_classification_lambda
    Description: Name of the Lambda function to trigger

Resources:
  NMMDocProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NMM_DocProcessingAfterExtractionQueueNew
      VisibilityTimeout: 300
      MaximumMessageSize: 1048576
      MessageRetentionPeriod: 240
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      SqsManagedSseEnabled: true

  LambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt NMMDocProcessingQueue.Arn
      FunctionName: !Ref LambdaFunctionName
      BatchSize: 10
      MaximumBatchingWindowInSeconds: 0

Outputs:
  QueueUrl:
    Description: URL of the created SQS queue
    Value: !Ref NMMDocProcessingQueue
    Export:
      Name: !Sub "${AWS::StackName}-QueueUrl"
  
  QueueArn:
    Description: ARN of the created SQS queue
    Value: !GetAtt NMMDocProcessingQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-QueueArn"
